SELECT data FROM (SELECT b.id, jsonb_build_object('id',b.id,'booking_id',b.id,'booking_reference',b.public_ref,'booked_by_user_id',b.created_by_external_user_id,'booking_owner_type',o.owner_type,'booking_owner_key',o.owner_key,'owner_display',o.display,'currency',r.currency,'payable',r.tier_pricing->>'payable','booking_status',CASE WHEN t.state='issued' OR EXISTS(SELECT 1 FROM flight_ticket_verifications v WHERE v.issue_id=t.id) THEN 'confirmed' WHEN (SELECT state FROM flight_ticket_outcomes s WHERE s.id=t.id)='not_issued' THEN CASE b.state WHEN 'held' THEN 'on-hold' ELSE b.state END WHEN t.id IS NOT NULL THEN 'in-progress' ELSE CASE b.state WHEN 'held' THEN 'on-hold' ELSE b.state END END,'issued_by_user_id',CASE WHEN (t.state='issued' OR EXISTS(SELECT 1 FROM flight_ticket_verifications v WHERE v.issue_id=t.id)) AND w.actor_role IN ('superadmin','b2b') THEN w.actor_id ELSE NULL END,'ticket_status',(SELECT state FROM flight_ticket_outcomes s WHERE s.id=t.id),'payment_state',CASE WHEN totals.refunded>0 THEN CASE WHEN totals.refunded=totals.captured THEN 'refunded' ELSE 'partially-refunded' END ELSE COALESCE(w.state,'unpaid') END,'reservation_id',w.id,'captured_amount',totals.captured::text,'refunded_amount',totals.refunded::text,'held_amount',totals.held::text,'released_amount',totals.released::text,'created_at',b.created_at,'updated_at',b.updated_at) data FROM flight_bookings b JOIN flight_reprices r ON r.id=b.price_id JOIN wallet_client_links cl ON cl.client_id=b.client_id JOIN wallet_owners o ON o.id=cl.owner_id LEFT JOIN flight_ticket_issues t ON t.booking_id=b.id LEFT JOIN wallet_operations w ON w.subject_kind='ticket_issue' AND w.subject_id=t.id LEFT JOIN LATERAL (
 SELECT COALESCE(sum(p.amount) FILTER(WHERE p.state='captured'),0) captured,
        COALESCE(sum(p.refunded_amount) FILTER(WHERE p.state='captured'),0) refunded,
        COALESCE(sum(p.amount) FILTER(WHERE p.state IN ('reserved','reconciliation')),0) held,
        COALESCE(sum(p.amount) FILTER(WHERE p.state='released'),0) released
 FROM wallet_operations p
 WHERE p.booking_id=b.id AND p.wallet_account_id=w.wallet_account_id AND p.currency=w.currency
   AND p.subject_kind IN ('ticket_issue','ticket_management')
) totals ON true WHERE $1='booking_payments' AND ($2::uuid IS NULL OR o.id=$2) AND ($3::uuid IS NULL OR b.id<$3) UNION ALL SELECT b.id,jsonb_build_object('id',b.id,'booking_id',b.id,'booking_reference',coalesce(b.booking_reference,b.public_ref),'booked_by_user_id',u.clerk_user_id,'booking_owner_type','agency','booking_owner_key',b.agency_code,'currency',b.currency,'payable',round(b.payable_minor::numeric/100,2)::text,'booking_status',b.status,'issued_by_user_id',CASE WHEN b.operation_id IS NOT NULL THEN w.actor_id ELSE NULL END,'payment_state',CASE WHEN totals.refunded>0 THEN CASE WHEN totals.refunded=totals.captured THEN 'refunded' ELSE 'partially-refunded' END ELSE coalesce(w.state,'unpaid') END,'reservation_id',w.id,'captured_amount',totals.captured::text,'refunded_amount',totals.refunded::text,'held_amount',totals.held::text,'released_amount',totals.released::text,'created_at',b.created_at,'updated_at',b.updated_at) FROM portal_import_bookings b JOIN portal_users u ON u.id=b.creator_id LEFT JOIN wallet_operations w ON w.id=b.operation_id LEFT JOIN LATERAL (
 SELECT COALESCE(sum(p.amount) FILTER(WHERE p.state='captured'),0) captured,
        COALESCE(sum(p.refunded_amount) FILTER(WHERE p.state='captured'),0) refunded,
        COALESCE(sum(p.amount) FILTER(WHERE p.state IN ('reserved','reconciliation')),0) held,
        COALESCE(sum(p.amount) FILTER(WHERE p.state='released'),0) released
 FROM wallet_operations p
 WHERE (p.id=b.operation_id OR (p.booking_id=b.id AND p.subject_kind='ticket_management'))
   AND p.wallet_account_id=w.wallet_account_id AND p.currency=w.currency
) totals ON true WHERE $1='booking_payments' AND ($2::uuid IS NULL OR $2=(SELECT owner_id FROM wallet_accounts WHERE id=w.wallet_account_id)) AND ($3::uuid IS NULL OR b.id<$3)) rows ORDER BY id DESC LIMIT $4
